;; auto-generated by nerd-fonts-gnerator.scm
(define-module (abbe packages nerd-fonts)
  #:use-module (guix packages)
  #:use-module (guix hash)
  #:use-module (guix download)
  #:use-module (guix build-system font)
  #:use-module ((guix licenses) #:prefix licenses:))

(define-public font-nerd-font-0xproto
	(package
		(name "font-nerd-font-0xproto")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/0xProto.tar.xz") (sha256 (base32 "09q4ipl3vvav3jbs0s14fqmd2wk70mc7i8mmplpj20jwcicm05ng"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-3270
	(package
		(name "font-nerd-font-3270")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/3270.tar.xz") (sha256 (base32 "0zcj5xhylyqxpwn6dzp28kh8xybhh4y9lva3smcqs7iklhbf8s31"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-agave
	(package
		(name "font-nerd-font-agave")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/Agave.tar.xz") (sha256 (base32 "1xxylrjb0zbq3kj14fx5d3lpb7abl0br6mkj961i391qyqlx01y3"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-anonymouspro
	(package
		(name "font-nerd-font-anonymouspro")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/AnonymousPro.tar.xz") (sha256 (base32 "1lq9wkf8c153jkjmhnddih12y9xd4gabbkgac0vx9j98hmy7yjqy"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-arimo
	(package
		(name "font-nerd-font-arimo")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/Arimo.tar.xz") (sha256 (base32 "1f7zljmljrp1dxkrhkyz8zh9ddv7l7m9br6gaygzxr26bq0vrwr0"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-aurulentsansmono
	(package
		(name "font-nerd-font-aurulentsansmono")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/AurulentSansMono.tar.xz") (sha256 (base32 "0wlwwgp1w7rqvqx66dkqwhz5flw75620fj9fb795hakpkjiya6yp"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-bigblueterminal
	(package
		(name "font-nerd-font-bigblueterminal")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/BigBlueTerminal.tar.xz") (sha256 (base32 "115cxnll1iyj75f5wi7b7pi5hgfa3b5kbx269alm9183h284lb23"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-bitstreamverasansmono
	(package
		(name "font-nerd-font-bitstreamverasansmono")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/BitstreamVeraSansMono.tar.xz") (sha256 (base32 "1s6jpg0vrdwgi9qyn0mbcy8r7h1lqw8z6q39wiin61szfn642a2k"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-cascadiacode
	(package
		(name "font-nerd-font-cascadiacode")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/CascadiaCode.tar.xz") (sha256 (base32 "1sg6czl3km7yi70vdcyb0ff1xkq1p4nalj0yh164gan3psp9mxss"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-cascadiamono
	(package
		(name "font-nerd-font-cascadiamono")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/CascadiaMono.tar.xz") (sha256 (base32 "0rrknf86kdwyjpnryp5870nmnq2sxjda8pgs93z23lh7hw758wln"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-codenewroman
	(package
		(name "font-nerd-font-codenewroman")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/CodeNewRoman.tar.xz") (sha256 (base32 "0p1wkmpzcrxw8qv5lf9fwsxqpjglhwim83amf7i8mmxdx1drzlj5"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-comicshannsmono
	(package
		(name "font-nerd-font-comicshannsmono")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/ComicShannsMono.tar.xz") (sha256 (base32 "1p35nmzl51mn2mk0g9fdcawvssv4v7bklxxmdx99357ihnlka26w"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-commitmono
	(package
		(name "font-nerd-font-commitmono")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/CommitMono.tar.xz") (sha256 (base32 "0jjzi98i28s3z2x8v7rakcdhgdf7jxzagj8snrylw2mvwn7mlgqp"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-cousine
	(package
		(name "font-nerd-font-cousine")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/Cousine.tar.xz") (sha256 (base32 "1ccq3sp8fqbi0njm9w2p6cf5r7avpan5fklwzpx4mknwbdqlrwdq"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-d2coding
	(package
		(name "font-nerd-font-d2coding")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/D2Coding.tar.xz") (sha256 (base32 "1c0chgbsmzlgq0vinbcz7ydkdhnram8cif8zx8kkpha31abna5n0"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-daddytimemono
	(package
		(name "font-nerd-font-daddytimemono")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/DaddyTimeMono.tar.xz") (sha256 (base32 "1nz4g26a4dx7ng5nv6bc4hg474inan1c00c86mdlmvl2vgmx6zbf"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-dejavusansmono
	(package
		(name "font-nerd-font-dejavusansmono")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/DejaVuSansMono.tar.xz") (sha256 (base32 "12x18i15723hxc1l6ng92m77wycjk0d6r15j34n1zsww5r6xwjxr"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-droidsansmono
	(package
		(name "font-nerd-font-droidsansmono")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/DroidSansMono.tar.xz") (sha256 (base32 "1mqd1qqbs9dxwmi98i4xw88c68l1bww1sqlsmxmn86368rjh14fk"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-envycoder
	(package
		(name "font-nerd-font-envycoder")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/EnvyCodeR.tar.xz") (sha256 (base32 "197g4jaljcb1yncn9rvh17n077p7bq0v59lvb9vqkq3lms5lzjni"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-fantasquesansmono
	(package
		(name "font-nerd-font-fantasquesansmono")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/FantasqueSansMono.tar.xz") (sha256 (base32 "079mk8xrri4r1d5k1w5fv1hb0hp3w499csirkd6yriss35sbhv9d"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-firacode
	(package
		(name "font-nerd-font-firacode")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/FiraCode.tar.xz") (sha256 (base32 "1i1vw65f00n6vjinyqr1bq5ni5r6g8cjinrfl5zhlqm0gagv5x6y"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-firamono
	(package
		(name "font-nerd-font-firamono")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/FiraMono.tar.xz") (sha256 (base32 "1i9bfxblx568wsjq7ks1kyyfn9k36i4r2an4n45mb46swc94n8n0"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-geistmono
	(package
		(name "font-nerd-font-geistmono")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/GeistMono.tar.xz") (sha256 (base32 "0wvc9hqkh7ap3ysklcin8k72706l72p2wyqv3bg5brzcmwcpy90g"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-go-mono
	(package
		(name "font-nerd-font-go-mono")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/Go-Mono.tar.xz") (sha256 (base32 "0j6rr0r7418f8a5bmxbagpmcf7bas2n53f0hg835zp2ikx9cx924"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-gohu
	(package
		(name "font-nerd-font-gohu")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/Gohu.tar.xz") (sha256 (base32 "0h8hjiqs3f6xwn7g4wg12xim65ybw2546nlf5p9ip4ymr7x17dks"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-hack
	(package
		(name "font-nerd-font-hack")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/Hack.tar.xz") (sha256 (base32 "1wxmd4jr4p11cfhzs5chyh649vps6sdz4bq28204npkd7wzh5fc9"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-hasklig
	(package
		(name "font-nerd-font-hasklig")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/Hasklig.tar.xz") (sha256 (base32 "1nja4r8sn67g3gn85xhb1h7p1pi96wl0hpg5b5gyd1z5llbgzc2g"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-heavydata
	(package
		(name "font-nerd-font-heavydata")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/HeavyData.tar.xz") (sha256 (base32 "1a3a1pixv97wlnai24zb8dhkzxb2llcarhjkfrgd4syhn37sdf7n"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-hermit
	(package
		(name "font-nerd-font-hermit")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/Hermit.tar.xz") (sha256 (base32 "1bh18rzwma7gzrx3ybw8g2s9k5xv7wx8ybnyas3qaxb03fpjqm93"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-ibmplexmono
	(package
		(name "font-nerd-font-ibmplexmono")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/IBMPlexMono.tar.xz") (sha256 (base32 "0hd04z17l2p21hij4a0gmwnlfxs7s8qqh08zf4pzqld10557gqlp"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-inconsolata
	(package
		(name "font-nerd-font-inconsolata")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/Inconsolata.tar.xz") (sha256 (base32 "1xy3h05zy49h91k7fqk8934p1f776w46i0bh510addg12w8mm7rc"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-inconsolatago
	(package
		(name "font-nerd-font-inconsolatago")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/InconsolataGo.tar.xz") (sha256 (base32 "0hcvh3s2rnnir03pszfmmwhbdsapx1b516phhjhb4wl0dqma9q39"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-inconsolatalgc
	(package
		(name "font-nerd-font-inconsolatalgc")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/InconsolataLGC.tar.xz") (sha256 (base32 "0bfwhzbz422kfdv9ppr83cc2aqqdn7g49f73zipl4yp5636gi5ks"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-intelonemono
	(package
		(name "font-nerd-font-intelonemono")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/IntelOneMono.tar.xz") (sha256 (base32 "0388390dlcprxhxxl57gy8rllwk8wsd92b5xwnqwb5f394gbc5m0"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-iosevka
	(package
		(name "font-nerd-font-iosevka")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/Iosevka.tar.xz") (sha256 (base32 "0dzkcn277jxiqrrqkyigw6jgd4lp9411r28rkpkwx6js6px27q8v"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-iosevkaterm
	(package
		(name "font-nerd-font-iosevkaterm")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/IosevkaTerm.tar.xz") (sha256 (base32 "1xccqkydkhmhq8akk23kkypqzcc2svyicxv9gblwzwbndjrfgmdm"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-iosevkatermslab
	(package
		(name "font-nerd-font-iosevkatermslab")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/IosevkaTermSlab.tar.xz") (sha256 (base32 "1svig63li8mjj2dkgiawgb82gpk8vkrkhih5cp0a6174bh4gycii"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-jetbrainsmono
	(package
		(name "font-nerd-font-jetbrainsmono")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/JetBrainsMono.tar.xz") (sha256 (base32 "01j0rkgrix7mdp9fx0y8zzk1kh40yfcp932p0r5y666aq4mq5y3c"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-lekton
	(package
		(name "font-nerd-font-lekton")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/Lekton.tar.xz") (sha256 (base32 "00cm8ni3cnmgzwj1ypvpcy8gvnlz31la51j411dpsdqsclbcp0i2"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-liberationmono
	(package
		(name "font-nerd-font-liberationmono")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/LiberationMono.tar.xz") (sha256 (base32 "1941pgw723a6my44g6idi56a88qvsi8lj3wl7slpr5l3pmfda2lx"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-lilex
	(package
		(name "font-nerd-font-lilex")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/Lilex.tar.xz") (sha256 (base32 "0qz23h6a77i4n8nmhb7hc56mkiwn3pj1s6dbl2v53fvypwghswm2"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-mplus
	(package
		(name "font-nerd-font-mplus")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/MPlus.tar.xz") (sha256 (base32 "0x7yvpkn32x50y9zpdpjrp1gvwwp4fsmjbqbnfzy14xhi03p0q2w"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-martianmono
	(package
		(name "font-nerd-font-martianmono")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/MartianMono.tar.xz") (sha256 (base32 "0zfcvi150yn274i41n66zr20hqgqb0r5v75q21bbgqvaysl4wj32"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-meslo
	(package
		(name "font-nerd-font-meslo")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/Meslo.tar.xz") (sha256 (base32 "1sjrsr7i3diz4h7wkrl8va7b40g4m1432dz6bpbm2nmp89aszg8s"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-monaspace
	(package
		(name "font-nerd-font-monaspace")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/Monaspace.tar.xz") (sha256 (base32 "0il36cm37pc6ndp96j32j0fqpqvwyv2xm3jr7d3zxwax1lcfilp5"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-monofur
	(package
		(name "font-nerd-font-monofur")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/Monofur.tar.xz") (sha256 (base32 "10gzx2r5a5f5jl192c6cwsil5k57aslmryfnilkv4g8417xmn0zb"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-monoid
	(package
		(name "font-nerd-font-monoid")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/Monoid.tar.xz") (sha256 (base32 "1fhsb326lc093ckrq2kz4vhr3ibrgp8y0mwa3qwdbapldxazz9f7"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-mononoki
	(package
		(name "font-nerd-font-mononoki")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/Mononoki.tar.xz") (sha256 (base32 "18zp94dnv6kp8l58151dybjf2w1gi99nh1rw098hkrf52gfrfdpb"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-nerdfontssymbolsonly
	(package
		(name "font-nerd-font-nerdfontssymbolsonly")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/NerdFontsSymbolsOnly.tar.xz") (sha256 (base32 "0y4r1rid5sjd9ihi6nkwy0sja792aghg21bpl3ri029b9pifx8xp"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-noto
	(package
		(name "font-nerd-font-noto")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/Noto.tar.xz") (sha256 (base32 "0vq9lgf4j6pi7pw3bfgfzkcdixnhikf4yys8fr0qql7mkwhj3rjb"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-opendyslexic
	(package
		(name "font-nerd-font-opendyslexic")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/OpenDyslexic.tar.xz") (sha256 (base32 "1yl1fm4pfjvxq411m6f8nycqjnpnhkllmlx16wjrjfqpaf63mm4n"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-overpass
	(package
		(name "font-nerd-font-overpass")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/Overpass.tar.xz") (sha256 (base32 "1plcn2qx2b08va65zagn1ybkh850157ii7x20nnrhp0h5f4rddzw"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-profont
	(package
		(name "font-nerd-font-profont")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/ProFont.tar.xz") (sha256 (base32 "11c3shv09dssjbjwa44y64dwq7dxn3gs23bfgvhkv51vshsx0fzy"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-proggyclean
	(package
		(name "font-nerd-font-proggyclean")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/ProggyClean.tar.xz") (sha256 (base32 "1l822wqrz7xmgnw535i9vl9gwjl4h037hi3xl0g4907kcdxwan0s"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-recursive
	(package
		(name "font-nerd-font-recursive")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/Recursive.tar.xz") (sha256 (base32 "1fngqsl1shbfbb1wcx77di42g65lm9f5fcw93m8dcvdzk5lxpxz5"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-robotomono
	(package
		(name "font-nerd-font-robotomono")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/RobotoMono.tar.xz") (sha256 (base32 "0g6yvz4vpfcylnshhyhwy5llz61n8m0a0vp4jgjhiir5svcd9krw"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-sharetechmono
	(package
		(name "font-nerd-font-sharetechmono")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/ShareTechMono.tar.xz") (sha256 (base32 "0mxsywg4gns31yzh1256y7pkbh0m6n3rf8gbb55mxw219ngskkyv"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-sourcecodepro
	(package
		(name "font-nerd-font-sourcecodepro")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/SourceCodePro.tar.xz") (sha256 (base32 "088vi947kavk1pkvbl68kv7nz84yvfkj725n2zn7ypq354kkm92n"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-spacemono
	(package
		(name "font-nerd-font-spacemono")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/SpaceMono.tar.xz") (sha256 (base32 "0f4kcm4i3y11mpxb9anmn8759zpv3lvril4shp3d4mfc0k3dgfdn"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-terminus
	(package
		(name "font-nerd-font-terminus")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/Terminus.tar.xz") (sha256 (base32 "04kzc594sb5vk8fd3ww9ip7jsy4vi6wmxdf6vzsvb2fgd98ck335"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-tinos
	(package
		(name "font-nerd-font-tinos")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/Tinos.tar.xz") (sha256 (base32 "14c31qv3ik0in44k98zjn398cffwgq8z7d5lx7sk6iv12hikrd11"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-ubuntu
	(package
		(name "font-nerd-font-ubuntu")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/Ubuntu.tar.xz") (sha256 (base32 "1bgk4hx26qn5ylsydsy9655isz05ir7154pv8dy4x5rpr144s9ba"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-ubuntumono
	(package
		(name "font-nerd-font-ubuntumono")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/UbuntuMono.tar.xz") (sha256 (base32 "15kkgx6i4f7zn6fdaw2dqqw3hcpl3pi4cy4g5jx67af8qlhqarrb"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-ubuntusans
	(package
		(name "font-nerd-font-ubuntusans")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/UbuntuSans.tar.xz") (sha256 (base32 "0jj4v198zshwhns5swrh02h2np3wgnv8lacn8b7jhmcd575cgy1y"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-victormono
	(package
		(name "font-nerd-font-victormono")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/VictorMono.tar.xz") (sha256 (base32 "03rh7rc6a934sgd1bs7h7y1swqwbv3g7zi624k6hd8v1m3f0j6xa"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-zedmono
	(package
		(name "font-nerd-font-zedmono")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/ZedMono.tar.xz") (sha256 (base32 "0yhb9fp7ahw8niki1njzk8pbl0iy53pgf7gx5yfc2ass9vjwky9d"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))


(define-public font-nerd-font-ia-writer
	(package
		(name "font-nerd-font-ia-writer")
		(version "3.2.1")
		(source (origin (method url-fetch) (uri "https://github.com/ryanoasis/nerd-fonts/releases/download//v3.2.1/iA-Writer.tar.xz") (sha256 (base32 "0vsppg62l35zhzlsa0fwczv09pk1nhrag9xhcaadipd962dv7c45"))))
		(build-system font-build-system)
		(license licenses:expat)
		(home-page "https://www.nerdfonts.com/")
		(synopsis "Iconic font aggregator, collection, & patcher. 3,600+ icons,\n50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font\nAwesome, Material Design Icons, Octicons, & more")
		(description "Nerd Fonts is a project that patches developer targeted\nfonts with a high number of glyphs (icons). Specifically to add a high number\nof extra glyphs from popular 'iconic fonts' such as Font Awesome, Devicons,\nOcticons, and others.")))
